package utils

// "github.com/IEatLemons/Blockchain/ethereum/ganache"

func privateKeys() []string {

	// Localhost private keys generated by ganache-cli
	ganacheKeys := []string{
		"0xf505909b40df8af5a3c7bb79d8ff3eddc6fd01442bfe8eae53551546a6fe1b6c",
		"0x422fbf1b2c27379da2fd5add9845979c7806a7fb1f8a40c7a1c19ccfccd0e333",
		"0x02856f46fd5b712a1608508b15c906fb63a62376f7a008261626d8833b977b79",
		"0xccd4d841a524afb6041b1b66dafaf5151663e4cb1b5b999958924c5ef88e4a69",
		"0x7c00d3ca4b7f1f381ffec7a4893a88bff695c5cd21f7124b4ae1fb9d6abeaaab",
		"0x34b01f50529511a406fb49a5031d534327ca8b4010e5b3b051215eb2aa146fe3",
		"0x378370ebcc4b1fc045a4268fb58b9db385a138f7e49b6b28a486c2c14c1d2b9f",
		"0xbe2141c8c285ab07c3d634ba987c5afdecb17ef03228438c4105ce203b58c8ed",
		"0xe0fb878aedbad67277a0cee91e42ad63a4d143e3a7996e6c57dff6e7ab4d2399",
		"0xd0c6ef8f9f45d81d5b62f2c2d250fd9c683d499999287f497d4c22b07637cdc8",
	}

	return ganacheKeys
}
