package utils

// "github.com/IEatLemons/Blockchain/ethereum/ganache"

func PrivateKeys() string {

	// Localhost private key generated by ganache-cli
	ganacheKey := "f505909b40df8af5a3c7bb79d8ff3eddc6fd01442bfe8eae53551546a6fe1b6c"

	return ganacheKey
}
